### ISSUE TITLE
Alerts - K8s generic storage alerts 

### ISSUE THREAD

**Issue by umangachapagain** [gluster/gluster-mixins#2]
PVCHardLimitNearingFull
StorageClass.PVCHardLimitNearingFull
StorageClass.PVCCountNearing Full
Namespace.PVCCountNearingFull
Namespace.EphemeralStorageLimitNearingFull

**Comment by cloudbehl** [comment]
@umangachapagain can you put more details regarding this from the doc.

**Comment by umangachapagain** [comment]
> @umangachapagain can you put more details regarding this from the Ju's slide doc

Yes. Working on it.

**Comment by umangachapagain** [comment]
Closing this as the Issue is raised on kubernetes-mixin project.
[https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/125](url)
