### ISSUE TITLE
Automated docker build and push to quay or docker

### ISSUE THREAD

**Issue by cloudbehl** [gluster/gluster-mixins#38]

**Comment by JohnStrunk** [comment]
I have created the container repo at quay.io/gluster-mixins, and added credentials to the Travis-CI job. Automated pushes should start w/ the next Travis build of master.

**Comment by JohnStrunk** [comment]
@cloudbehl Looks like Travis is failing on the deploy step, perhaps because `.travis/push_container.sh` is not executable.

**Comment by shtripat** [comment]
Closing as required PR merged. There would be separate issue created for quay.io push

**Comment by JohnStrunk** [comment]
Looks like I typo-d the credentials. I re-entered them, restarted the build, and now we have a container in Quay. :tada:

**Comment by cloudbehl** [comment]
Yaayyy :+1:
